version: '3'
services:
  ils:
    container_name: ils
    pull_policy: build
    build: .
    environment:
      - PORT=${PORT}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - R_SERVER_IP=${R_SERVER_IP}
    ports:
      - 3005:3000
    labels:
      - "traefik.http.routers.ils.rule=Host(`ils.cheekysim.com`)"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik_default